### ISSUE TITLE
Array flattening

### ISSUE THREAD

**Issue by jmatsushita** [d-plaindoux/masala-parser#122]
Hi @nicolas-zozol 

My conversion of [ch16/csv1.hs](http://book.realworldhaskell.org/read/using-parsec.html) is almost complete, but (maybe unsurprisingly) the types (cough) are giving me some trouble.

I now don't quite understand how masala deals with Lists/Arrays. For instance, I wasn't expecting to have to map the result of `line` into singleton lists, thinking that the `rep()` would properly create an Array of Array (or a List of Lists). I'm also not sure why the single cell doesn't end up within a singleton Array too. Is there something going on behind the scenes with Array/List flattening or am I misunderstanding something?

```js
const { Streams, C, F } = require("@masala/parser");

const remainingCells = () =>
  F.try(
    C.char(",")
      .drop()
      .then(cells())
  ).or(F.returns([]));

const cellContent = () =>
  F.not(C.charIn(",\n"))
    .optrep()
    .map(r => r.array().join(""));

const cells = () =>
  cellContent()
    .then(F.lazy(remainingCells).opt())
    .map(([first, next]) => [first].concat(next.orElse([])));

const eol = () => C.char("\n");

const line = () =>
  cells()
    .thenLeft(eol())
    // Not sure why I have to wrap each line in an Array
    // Maybe because I unwrapped the List in cells?
    .map(r => [r]);

const csvFile = () =>
  line()
    .rep()
    .thenLeft(F.eos())
    .map(a => a.array());

const stream = Streams.ofString("test,no\na,b\nlook_ma_only_one_cell\n");

const parsing = csvFile().parse(stream);
console.log("parsing", JSON.stringify(parsing));
console.log("parsing.value", JSON.stringify(parsing.value));
```

**Comment by jmatsushita** [comment]
To be more informative: the code above outputs:
```
parsing.value [["test","no"],["a","b"],"look_ma_only_one_cell"]
``` 

and I was expecting to see instead:
```
parsing.value [["test","no"],["a","b"],["look_ma_only_one_cell"]]
```

**Comment by nicolas-zozol** [comment]
`List` is used only with `rep()` and `optrep()` . It's well encapsulated in `cellContent()` or `csvFile ()`
Note that in `cellContent()` you can just write `.map(r => r.join(''));`

I'll dig in that tonight. Can I use your example inside our lib for next release ?

**Comment by jmatsushita** [comment]
> you can just write .map(r => r.join(''));
> I'll dig in that tonight.

👍 

>  Can I use your example inside our lib for next release ?

That'd be awesome :)

**Comment by jmatsushita** [comment]
Here's a minimal-ish example, with a custom parser since it corresponds to the approach I'm using in my actual code base:
```
const {
  Streams,
  F,
  Parser,
  parsec: { response }
} = require("@masala/parser");

const text = text =>
  new Parser((input, index = 0) => {
    // console.log("input.unsafeGet(index)", input.unsafeGet(index));
    const current = input.get(index);
    if (current && current.value && text === current.value) {
      return response.accept(current.value, input, index + 1, true);
    }
    return response.reject(input, index, false);
  });

const parse = () =>
  text("open")
    .debug("open")
    .then(
      F.not(text("close"))
        .optrep()
        // If the below is uncommented then the Array is flattened
        // .map(({ value }) => value)
    )
    .debug("content")
    .then(text("close"))
    .debug("close");

const stream = Streams.ofArray(["open", "a", "b", "close"]);

const parsing = parse().parse(stream);
console.log("parsing", JSON.stringify(parsing));
console.log("parsing.value", JSON.stringify(parsing.value));
```

The above code outputs:
```
parsing.value ["open",{"value":["a","b"]},"close"]
```

When I uncomment the `.map(({ value }) => value)` in order to unwrap the `.value` this is what I get:
```
parsing.value ["open","a","b","close"]
``` 

Whereas I would expect an Array of Arrays for the content:
```
parsing.value ["open",["a","b"],"close"]
```

**Comment by nicolas-zozol** [comment]
Here is the answer for the first problem:

```js
import { Streams, C, F } from "@masala/parser";

const remainingCells = () =>
        // no need to try here, because F.lazy(remainingCells) is opt()
        C.char(",")
            .drop()
            .then(cells());   // not sure for lazy


const cellContent = () =>
    F.not(C.charIn(",\n"))
        .rep()   // removed optrep() to avoid to deal with an empty last line. Let suppose no empty cell.
        .map(r => r.array().join(""))
        .debug('cellContent');

const cells = () =>
    cellContent()
        .then(F.lazy(remainingCells).opt())
        .debug('then')
        .map(([first, next]) => {
            console.log({first}, {next}, [first].concat(next.orElse([])));
            return [first].concat(next.orElse([]))
        })  ;

const eol = () => C.char("\n");

const line = () =>
    cells()
        .thenLeft(eol())
        // Each line must be wrapped to have at the end an array of array
        // Because of recursive nature, we must make a test : did we got recursion ?
        .map(r => [  Array.isArray(r)? r : [r]  ]);

const csvFile = () =>
    line().debug('got line:')
        .rep()
        .thenLeft(F.eos())
        .map(a => a.array());


const stream = Streams.ofString("test\na,b,c\n");
const parsing = csvFile().parse(stream);
console.log("parsing", JSON.stringify(parsing));
console.log("parsing.value", JSON.stringify(parsing.value));
```

Let have `a = C.char('a'), b=C.char('b') ;`  `a` and `b` are both `SingleParser<string>`, and `c=a.then(b)` is an `ArrayParser<string>`. It can be determined at compile time.

But because of the recursive nature of your code, we don't know if the `then` occurred. So we must make a test : ` .map(r => [  Array.isArray(r)? r : [r]  ]);`. Obviouly it can be tricky because in other situations, ` r` could be an array by nature (not because of then)... That's the reason why we introduced List when values of Parsers are innocent arrays.

**Comment by nicolas-zozol** [comment]
For the second, it's more straightforward: the `optrep()` produces a `List`. You could go away from `{value:[a,b,c]}`  with:

```js
F.not(text("close"))
                .optrep()
                .map(list => list.array())
```

But you would have `open.then([a,b,c]).then(close)` ; But `SingleParser.then(ArrayParser)` resolves as an `ArrayParser`.

So you need:

```js
F.not(text("close"))
                .optrep()
                .map(list => [list.array()] )
```
Your repetition is enclosed in its array. Which is wrapped by 'open' and 'close'

**Comment by d-plaindoux** [comment]
Well the original problem came from the `then`implementation:

```js
    // Parser 'a 'c => Parser 'b 'c -> Parser ??? 'c
    then(p) {
        return this.flatMap(a =>
            p.map(b => {
                let result = list(a).append(list(b)).array();
                if (result.length === 1) {
                    return result[0];
                } else {
                    return result;
                }
            })
        );
    }
```

The implementation implicitly transform an Array with element unwrapping the array and returning the embedded singleton. In addition. The problem with this implementation it's the returned type because it depends on the context as mentioned in the typescript specification:

```ts
interface VoidParser extends IParser<void> {
    then<Y>(p: SingleParser<Y>): SingleParser< Y>;
    then<Y>(p: ArrayParser<Y>): ArrayParser<Y>;
    // ...
}
```

### Case 1 
Should be stay with this implementation or should we be formal and remove this optimisation replacing it by a `pair` object in order to conform to the initial parsec specification ?

The root problem is related to a property which is not reflected by the pair type which is:

```
    (P1.then(P2)).then(P3) == P1.then(P2.then(P3))     // Associativity
```

### Case 2
Remove the unwrapped list

### Case 3 
Stay with the current implementation

**Comment by d-plaindoux** [comment]
AFAIC in think the case 2 preserve the associativity property and prevent type confusion even we deal with a list with on element. The unwrapping can be asked by an additional function for instance.

**Comment by nicolas-zozol** [comment]
This comes back to `P.flattenDeep()` in #16, and associativity explained [here](https://github.com/d-plaindoux/masala-parser/issues/67#issuecomment-290131875).

Clearly, List is a gain, so Case 3 is better than Case 1. Recursivity has shown a difficulty, but I guess that recursivity by definition needs a test.

I didn't understood the case 2. By chance, the `list` is a trick that allow us to deal with VoidParser, SingleParser and ArrayParser having to classify each parser manually. We could formerly have to declare `new VoidParser() ...` and write three implementations of `then`.  I don't like that 😄.

Could you give an example for case 2 ?

**Comment by nicolas-zozol** [comment]
I think that to be mathematically, `then()` should also return a `list()`. Currently, 

    let p = F.startWith([1,2])
         .then(C.char('a'))
         .then(C.char('b'))
         .then(C.char('c'));

will return [1,2,a,b,c] instead of maybe [ [1,2], 'a', 'b', 'c']. It might be boring to call `.array()` on those list, because currently 99% of my parsing are standard stuff.

We could make a terminator option to automatically unwrap for lazy people in known context.

**Comment by nicolas-zozol** [comment]
Well, the most logical thing would be to change all the code and make `then`, `rep` and `and()` return a `List()` .

Shit happens..... The sooner, the better.
```js
 let p = F.startWith([1,2])
         .then(C.char('a'))
         .then(C.char('b'))
         .then(C.char('c').opt())
        .array() // as a convenient function
```

**Comment by nicolas-zozol** [comment]
There should also be a `Void` symbol, as `nop()` and `drop()` returns `[]`;

**Comment by nicolas-zozol** [comment]
Works correctly now
