### ISSUE TITLE
F.layer(x).and(y) ?

### ISSUE THREAD

**Issue by jmatsushita** [d-plaindoux/masala-parser#123]
Hi @nicolas-zozol 

I've been trying to parse the same sequence with 2 different parsers (for instance, one which returns all elements raw, the other which parses elements into a data structure), but rather than doing 2 complete passes, I'm wondering if it would be possible to do the same as `F.try(x).or(y)` but instead of backtracking when `x` fails, backtrack when `x` completes (and fail if `x` fails), then do `y`. 

This would in effect layer the results of `x` and `y`, doing the 2 passes only locally.

Maybe I'm missing a more idiomatic way to do this?

Cheers,

Jun

**Comment by nicolas-zozol** [comment]
Let says you want a X data structure and a Y as an array of tokens.

Maybe you are looking for ParserStream and Genlex. It will give you a stream of tokens defined as low level parsers.
Then you can parse with a regular grammar, saving in your data structure {x:X, y:Y} and split that at the end.
Genlex is the new feature of v0.8 and has not been well documented.

https://github.com/d-plaindoux/masala-parser/blob/master/src/test/genlex/proposition.js

https://github.com/d-plaindoux/masala-parser/blob/master/src/test/genlex/genlex-test.js

Unfortunately, Genlex is quite hard to debug ( #118) as you must guess by yourself which token has been accepted, and which has failed. I have some clues to handle that problem.

**Comment by jmatsushita** [comment]
I'd like to do this staying at the same level of abstraction of parser combinators if I could. 

Here's a somewhat contrived example, with the commented code at the bottom an example of how such a backtracking higher order combinator would work:
```
const {
  Streams,
  F,
  Parser,
  parsec: { response }
} = require("@masala/parser");

const text = text =>
  new Parser((input, index = 0) => {
    // console.log("input.unsafeGet(index)", input.unsafeGet(index));
    const current = input.get(index);
    if (current && current.value && text === current.value) {
      return response.accept(current.value, input, index + 1, true);
    }
    return response.reject(input, index, false);
  });

const count = () =>
  F.try(text("a").map(() => ({ a: 1 })))
    .or(text("b").map(() => ({ b: 1 })))
    .optrep()
    .map(r =>
      r
        .array()
        .reduce(
          (acc, f) =>
            acc[Object.keys(f)[0]]
              ? { ...acc, [Object.keys(f)[0]]: acc[Object.keys(f)[0]] + 1 }
              : { ...acc, ...f },
          {}
        )
    );

const parse_raw = () =>
  text("open")
    .then(F.not(text("close")).optrep())
    .then(text("close"));

const parse_count = () =>
  text("open")
    .then(count())
    .then(text("close"));

const stream = Streams.ofArray(["open", "a", "b", "a", "close"]);

const parsing_raw = parse_raw().parse(stream);
console.log("parsing_raw.value", JSON.stringify(parsing_raw.value));
// parsing_raw.value ["open",{"value":["a","b","a"]},"close"]
const parsing_count = parse_count().parse(stream);
console.log("parsing_count.value", JSON.stringify(parsing_count.value));
// parsing_data.value ["open",{"a":2,"b":1},"close"]

// const parse_layer = () =>
//   text("open")
//     .then(F.layer(count()).and(F.not(text("close")).optrep()))
//     .then(text("close"));
// parsing_layer.value ["open",[{"a":2,"b":1},["a","b","a"]],"close"]
``` 

The fact that my OP and this example's `parse_raw` returns the raw Array of tokens is incidental and `F.layer` could layer several parsers which actually do something.

**Comment by nicolas-zozol** [comment]
@d-plaindoux invocation 😄

**Comment by nicolas-zozol** [comment]
OK. the key points are
- backtracking multiple times if multiple `and()` 
- stay local: it could make many passes only in a very restricted part of the input
- with `F.layer(a).and(F.layer(b)).and(F.layer(c))`, we would have `[x,y, z]` as a response

It might be interesting. If there is a `or`, there must a `and` :smile:

**Comment by nicolas-zozol** [comment]
I have something working, but now we go again on list: How do we treat:

    F.layer(x).and(y).and(z)

Should it be `List([a,b,c])`, or `[[a,b],c]` that won't preserve associativity. Like for #122

**Comment by nicolas-zozol** [comment]
Tested and covered by d4c7e6acf6b4af588804a3e665835eebc45b3b53
