### ISSUE TITLE
Separate ParseException with business exceptions 

### ISSUE THREAD

**Issue by nicolas-zozol** [d-plaindoux/masala-parser#126]
A user that codes : `throw 'illegal state exception'` in his parser will have the parsing continuing instead of having a hard stop at given index.

**Comment by d-plaindoux** [comment]
The user should not use exception in this case but a Try or Either data type if he wants to manage seamlessly such cases preventing parsers to be broken.

**Comment by d-plaindoux** [comment]
Modifying the behaviour of Try which is monadic it's not the right solution. We should not alter basic behaviour holds by neutral and standard ADT.
