### ISSUE TITLE
then should always returns a list

### ISSUE THREAD

**Issue by nicolas-zozol** [d-plaindoux/masala-parser#127]
There are some complications with #110 , for example with letters or recursive stuff : if there is one letter, it will be a single object, if many, it will be a list. 

A parser should have `single()` operation that maps to the first element of the list. 

The question is : should it throw an exception if it's not a single object. It must wait for a more complex #126 to be closed for that.

**Comment by d-plaindoux** [comment]
Agree with this topic. A parser returning A | List[A] is problematic and does not habit a "correct" abstract data type.

**Comment by nicolas-zozol** [comment]
`then` return indeed a Tuple()
