### ISSUE TITLE
thenReturns should be renamed

### ISSUE THREAD

**Issue by nicolas-zozol** [d-plaindoux/masala-parser#128]
`thenReturns` does not return a List, but a single value, so it should be renamed to avoid confusion

**Comment by d-plaindoux** [comment]
What is the relationship between `thenReturns` and the List?

**Comment by d-plaindoux** [comment]
If we change it to `thenRetturn` is it acceptable?

**Comment by d-plaindoux** [comment]
In fact, `thenReturns` do not return a constant but a parser producing a value. For instance, taken from the seminal paper written by Erik Meijer this is the `return`definition:

```
return :: a → Parser a
(>>=) :: Parser a → (a → Parser b) → Parser b
```

**Comment by nicolas-zozol** [comment]
calling it `.returns(P)` is ok for me.
