### ISSUE TITLE
Operation Parser

### ISSUE THREAD

**Issue by nicolas-zozol** [d-plaindoux/masala-parser#13]
Creating a simple operation parser mainly for educational purposes

**Comment by nicolas-zozol** [comment]
This works :

**Comment by d-plaindoux** [comment]
Parsec lets you define LL(1) parser. Such parser can't be left recursive by definition. For this purpose `exp` must be designed using two parsers as shown in the next example:

```
exp   = sexp (op exp)?
sexp = number | '(' exp ')'
```

**Comment by nicolas-zozol** [comment]
I found a general solution that works with two precedences. I use `*` and `+`. It should work with no problem with `-`and `/`.

Implementing general solution :
```
// grammar terms 
E -> T E'
 E' -> + TE'  |  eps
 T -> F T'
 T' -> * FT'  |  eps
 F -> NUMBER | ( E )

 E== expr
 T == subExpr
 E'== optPlusExpr
 T' == optMultExpr
 F == terminal

// pseudo masala
 expr -> subExpr optPlusExpr'
 optPlusExpr -> ( + then subExpr then F.lazy(optPlusExpr) ).opt()
 subExpr -> terminal then optMultExpr
 optMultExpr -> ( * then terminal then F.lazy(optMultExpr) ).opt()
 F -> F.try( '(' then expr then ')' ).or(N.litteral)
```
