### ISSUE TITLE
GenLex is mutable

### ISSUE THREAD

**Issue by nicolas-zozol** [d-plaindoux/masala-parser#132]
GenLex is mutable with set/update/remove functions. This should change by returning each time a new GenLex.

**Comment by d-plaindoux** [comment]
Shame on me!

**Comment by nicolas-zozol** [comment]
No, it's my implementation. I've redesigned it. https://github.com/d-plaindoux/masala-parser/blob/tuple/src/test/genlex/proposition.js

By the way, in my opinion, mutability is not that evil :smile:

**Comment by nicolas-zozol** [comment]
:beer: ?
