### ISSUE TITLE
Add a `repSplit(p)` function to `Parser`

### ISSUE THREAD

**Issue by nicolas-zozol** [d-plaindoux/masala-parser#138]
A simple exemple would be for bullet points

```
* bullet 1
* bullet 2
* bullet 3
```

If we use `bullet().then(eol()).rep()`, then the last `eol()` is eaten by the parser, so we can't separate easily bullet block by at least two `eol()`.

So the idea would be `bullet().repSplit(eol())` and would return a `TupleParser<Bullet>`.

Other option maybe more general but maybe less in the Parsec philosohy is to make 

```js
bullet().then(eol())
.rep() // eat last '\n'
.backdrop(1); // go back 1 character
```

It could be use in many more situations (including bad ones)

**Comment by d-plaindoux** [comment]
You can use the lookup function which parses but do not consume parsed items:
```
bullet().lookahead(eol())
```

**Comment by d-plaindoux** [comment]
This should be written:
```
bullet.then(eol().then(bullet()).rep()
```

Indeed the `rep` parser can be generalized with start, join and end parsers.

**Comment by nicolas-zozol** [comment]
The `back()` function would not help, because for example if the document finishes at the `* bullet3` without last `\n`, applying the `back()` function would move the cursor before the `3`.

**Comment by nicolas-zozol** [comment]
For the record, here is a way to go back if ever needed.
```js
const parser = C.string('this is wanted').then(C.char(';'));

const backParser = new Parser(function (input, index) {
    return parser.parse(input, index)    // parsing with regular parser
        .fold(    // then modifing the response
            accept =>
                response.accept(
                    accept.value,
                    accept.input,
                    accept.offset - 1,   // moving back of one offset
                    accept.consumed
                ),
            reject =>
                response.reject(
                    reject.input, reject.offset, reject.consumed
                )
        );
});

const resp = backParser.parse(Streams.ofString(line));
```
