### ISSUE TITLE
Thoughts about Bennu?

### ISSUE THREAD

**Issue by ccorcos** [d-plaindoux/masala-parser#39]
I started writing my own parser combinators library until I came across this project and [Bennu](https://github.com/mattbierner/bennu). Bennu hasn't been worked on in a while, but it seems quite mature. Its really lightweight and has all the bells and whistles I could imagine.

Any reason you are deciding to build a library of your own rather than using Bennu? Just curious, what are you guys using this library for?

**Comment by d-plaindoux** [comment]
Well before starting my own parser combinator I also came across Bennu. First the implementation has been written using the Khepri language. Then any contribution should be done using this language if we want to be coherent. As a consequence this language should be learned first! Second the current library only works for character based parsers which is a weak version compared to the one describe in the seminal paper.

These reasons convince me to write my own library from scratch with two major components:
- the parser (based on parsec specification) and
- the stream (which is a pure abstraction).

Then we are able to write parsers dedicated to stream of structured data and not only characters. For instance this is used by tokeniser[1] parser which can be combined with a more high level parser has shown in the JSon parser[2]. This can be compared to OCaml GenLex [3].

Finally this has been done just for fun at the beginning but contributions are now in progress and a full and complete first Markdown parser is in design and development process.  

[1] https://github.com/d-plaindoux/parsec/tree/master/src/lib/genlex
[2] https://github.com/d-plaindoux/parsec/blob/master/src/lib/standard/jsonparser.js
[3] https://caml.inria.fr/pub/docs/manual-ocaml/libref/Genlex.html

**Comment by ccorcos** [comment]
I definitely agree about having to contribute by writing Khepri.

> Second the current library only works for character based parsers which is a weak version compared to the one describe in the seminal paper.

This library only supports strings? Is that what you're saying?

> For instance this is used by tokeniser[1] parser which can be combined with a more high level parser has shown in the JSon parser[2].

I'm not sure how genlex works. Why are we using classes though? Isn't the goal here to be functional?

> a full and complete first Markdown parser is in design and development process

Awesome! this is exactly what I'm trying to build. I want to have a flexible syntax that can render with a component library like React. I'm basically on my third attempt writing this parser and i think I've finally figured it out. I'm happy to collaborate with you if you're interested!

Here are a few things I've figured out so far: you can't parse markdown eagerly one character at a time to the end, you need to make multiple passes in order to enforce precedence. For example `*[*](*)` should parse into `*<a href="*">*</a>` and no` <em>[</em>](*)`. If you parse everything one character at a time inside an either, you'll still run into the italics token first and won't generate the proper output.

So the first step is to create a token stream of text and special character tokens. Then you need to pass over this token stream into another token stream starting with the highest precedence. For example:

```js
string = '*[hello **world**](*)'

tokens = [
  {type: 'stars', length: 1},
  {type: '['},
  {type: 'text', value: 'hello '},
  {type: 'stars', length: 2},
  {type:'text', value: 'world'},
  {type: 'stars', length: 2},
  {type: ']'},
  {type: '('},
  {type: 'stars', length: 1},
  {type: ')'},
]

// first pass with link
tokens2 = [
  {type: 'stars', length: 1}, 
  {type: 'link', url: '*', children: [{
    {type: 'text', value: 'hello '},
    {type: 'stars', length: 2},
    {type:'text', value: 'world'},
    {type: 'stars', length: 2},
  }]}
]
```

Then you can recursively run a pass with the tokens with less precedence.

The last tricky thing is how handling bold and italics. You need to parse both of them together in the same pass disambiguating these cases: `***bold and italic** just italic*` and `***bold and italic* just bold**` along with more annoying cases like `*italic ** not bold*`.

Bennu has a very interesting way of handling this stuff monadically with this "user state" concept -- its pretty freaking cool: https://github.com/mattbierner/bennu/wiki/User-Data#interacting-with-user-data-during-parsing

Anyways, I'm more than happy to help out. Simply rewriting Bennu in JavaScript seems like a solid place to start though no?

**Comment by d-plaindoux** [comment]
> This library only supports strings? Is that what you're saying?

I'm wrong! All examples are based on string analysis but the internal stream representation seems to be a Lazy data stream[1].

For the markdown parser your approach based on token stream is awesome. It requires independent parser with transformation stages for tokens reduction. Then each stage has a clean and specific goal.

For this purpose may be parsers pipelining[2] (or user state as mentioned) can be helpful for such transformations. Don't know which one is the most appropriate but one important feature is the position. In fact if we have multiple transformations the initial (source) position must be well managed - and preserved by propagation - if we want to provide clean and clear error messages when any problem occurs during a parse stage. 

If you want to help to improve/suggest functional aspects of this parsec implementation you are welcome!

[1] http://blog.mattbierner.com/incremental-parser-combinators-in-javascript/
[2] https://github.com/d-plaindoux/parsec/blob/master/src/lib/parsec/parser.js#L103

**Comment by nicolas-zozol** [comment]
Bennu is written in an almost unknown language, and the home page talks about brainfuck and fantasy. Does it make it a bad project ? Certainly not, but on the long term it, and mainly Khepri language, will have a negative impact. And while @d-plaindoux does it for fun, I do open source for money 😅

More seriously, I'm here to make it comprehensive by other people. My brother @simon-zozol  codes also some parts, and you are welcome to bring more subtle details to the markdown parser. Parser-combinator JS is not an easy lib to start, but as exemples are coming in the /src/standard directory, it will become more and more easy. I've done my first day at a start-up for real case parsing, and it works, so this will give soon other working examples.

I suggest you to look at the Phenomic library, also written by a French in the Toulouse area. It takes markdown content and uses React to create static web site (don't know how🙂). My second goal is also to use Parsec to generate React components from markdown, and then to put it inside Phenomic.

**Comment by nicolas-zozol** [comment]
@ccorcos: I have started a 1.0 roadmap in #42 . Feel free to send us your ideas here.

**Comment by ccorcos** [comment]
sweet. lets continue there
