### ISSUE TITLE
FlattenDeep

### ISSUE THREAD

**Issue by d-plaindoux** [d-plaindoux/masala-parser#48]
This method is unused. I think this stuff is useless since map and flatmap provide the best approach for data transformation.

**Comment by nicolas-zozol** [comment]
It was first used in markdown, then replaced with better handling of thenLeft and thenRight. However, it was used on then hotelub project: to search a date in the text:

```
// Search 24/11/2016 and transforms into 2016-11-23, or search directly  2016-11-23
function date() {
    return dateDigits()
        .then(P.charIn('-/').thenReturns('-'))
        .then(dateDigits())
        .then(P.charIn('-/').thenReturns('-'))
        .then(dateDigits())   // Now we have something like [ [ [], [] ], [] ]
        .flattenDeep()   // ['24', '/' , '11', '/', '2016'] 
        .map(dateValues=>dateValues[4] > 2000 ? dateValues.reverse() : dateValues)
        .map(dateArray=>dateArray.join(''));
}
```
How would you use flatmap in this case ? I have put difficulty: 3/3 in the[ docs](https://github.com/d-plaindoux/parsec/blob/master/documentation/parser-core-functions.md) :) So I don't think I have understood it's full potential.

**Comment by d-plaindoux** [comment]
// Search 04/11/2016 and transforms into 2016-11-04, or search directly  2016-11-04
function date() {
    return sequence(dateDigits(),
P.charIn('-/').thenReturns('-'))
        .then(dateDigits())
        .then(P.charIn('-/').thenReturns('-'))
        .then(dateDigits())   // Now we have something like [ [ [], [] ], [] ]
        .flattenDeep()   // ['24', '-' , '11', '-', '2016'] 
        .map(dateValues=>dateValues[4] > 2000 ? dateValues.reverse() : dateValues)
        .map(dateArray=>dateArray.join(''));
}

**Comment by nicolas-zozol** [comment]
Nice.

**Comment by nicolas-zozol** [comment]
`flattenDeep` is still present in code and tests.

**Comment by nicolas-zozol** [comment]
Closed as the then() is cool now
