### ISSUE TITLE
Token Bundle: accept any date

### ISSUE THREAD

**Issue by nicolas-zozol** [d-plaindoux/masala-parser#64]
It could be nice to accept `date('MM-D-YYYY, h:mm:ss a')`. It should not be that complicated for dates that does not require languages.

MMMM is difficult and moment.js uses some localized files, wich is out of masala's scope. https://github.com/moment/moment/tree/develop/locale

**Comment by aychtang** [comment]
@nicolas-zozol:

Will you be working on an implementation for this yourself or are you open to PRs? I'm working on this functionality for my app anyway.

**Comment by nicolas-zozol** [comment]
Hi, yes please 👍 
You can do it at this place : https://github.com/d-plaindoux/masala-parser/blob/master/src/lib/standard/token-bundle.js

Another option is to make a DateBundle()

    const date = new DateBundle()
    date.useLocaleData(....some json from moment.js....)
    C.string("start at ").drop().then (date.parse("dd MM YYYY"));

Other users will be able to use https://github.com/moment/moment/tree/develop/locale and/or to extend this bundle more easily if they come from Java/Angular world.

**Comment by d-plaindoux** [comment]
We are open to PRs of course ... 😉

**Comment by nicolas-zozol** [comment]
Close mainly because of #96 .
