### ISSUE TITLE
Rename thenLeft and thenRight

### ISSUE THREAD

**Issue by nicolas-zozol** [d-plaindoux/masala-parser#67]
I think it's not easy to understand for beginners.

We could change `x.thenLeft(y)` by `x.thenSkip(y)` and `x.thenRight(y)` by `x.thenKeep(y)`;

What do you think ?

**Comment by d-plaindoux** [comment]
I agree these parsers can be difficult to understand.
Frankly speaking i prefer something different like:

```
x.forget()
```

Therefor we have the semantic equivalences:
* `x.thenLeft(y) === x.then(y.forget())`
* `x.thenRight(y) === x.forget().then(y)`

**Comment by nicolas-zozol** [comment]
So if we have:

```js
x.forget()
   .then(a)
   .then(b)
   .then(y.forget())
   .then(c)`
````

, is it better to have has value `[a,b,c]`, or `[ [a,b],c]` like we have presently. I think [a,b,c] is also better to catch - and we could drop `sequence()`.

**Comment by nicolas-zozol** [comment]
Another problem with `then()` is that it's go against the `thenable()` in Promise/A+ that replace data, instead of adding to a result.
Instead of `then`, it should be `concat()`, but I'm not sure it's associative like fantasy land requires it: https://github.com/fantasyland/fantasy-land#concat-method

`a.concat(b).concat(c)` is equivalent to `a.concat(b.concat(c))`

would give:

```js
p.then(p2).then(p3)
// ===
p.then(p2.then(p3))
```

I'm testing this before :)

**Comment by nicolas-zozol** [comment]
So considering the stream "23 xy 34" and parsers:

```
 p1= N.integer, p2=C.string('xy'), p3=N.number;

p1.then(p2).then(p3) // now => [  [23, xy], 34  ]
p1.then(p2.then(p3)) // now => [  23, [xy, 34 ]]

```

With the `[a,b,c]` proposition, `p1.concat()` would be associative. We could still keep `then()` and implement `concat()` aside, but I'm not sure this `then` is useful. I might be wrong !!!!

We could also rename `thenReturns()` to `then()` that does the usual JS `then()`

**Comment by nicolas-zozol** [comment]
One thing is how to deal with `rep()` and `occurence()`. Using:

```js
// p1.rep() maps to 2x, p2 to 4y
p1.rep().concat(p2.occurrence(4))
```
We should still have:  `[ [x,x],  [y,y,y,y]]` and not a flattened stuff

**Comment by d-plaindoux** [comment]
We should always wrap the result in an array. Then the global behaviour relies on catenation.

**Comment by d-plaindoux** [comment]
After a deep rework the chosen solution is a little bit different. Only optrep and rep parsers change. They return a List and not an Array as expected.

**Comment by d-plaindoux** [comment]
Current solution available in branch 'result-combiner'

**Comment by d-plaindoux** [comment]
As a consequence this new version is not compatible with parsers written using there previous version.

**Comment by nicolas-zozol** [comment]
I have played with it and it's pretty nice. I've added a few test and a redirection from `concat()` to `then()`. It's free and satisfies fantasy-land.

**Comment by nicolas-zozol** [comment]
Oups:
Test time with result-combiner:

![capture d ecran 2017-05-07 a 09 31 51](https://cloud.githubusercontent.com/assets/912634/25778764/1f7e550c-3308-11e7-8cef-6041e60cbfb2.png)

Test time before:

![capture d ecran 2017-05-07 a 09 31 06](https://cloud.githubusercontent.com/assets/912634/25778769/34cefcae-3308-11e7-810f-d2a62722c404.png)


Probably with this line or similar:

![capture d ecran 2017-05-07 a 09 28 34](https://cloud.githubusercontent.com/assets/912634/25778777/75b25d38-3308-11e7-8b5b-480d28060b9a.png)

I'm totally ok with the syntax. I will try an implementation with Symbols. I think it will be faster.

**Comment by nicolas-zozol** [comment]
Note that `then` is not a *keyword* in js libs, including RxJS or RxJava. So it's ok to use this word as it explains clearly the flow.

**Comment by nicolas-zozol** [comment]
I've tried a mutable version  of `list.append()`, it has no effect on perfs. I think we should let it as is and check later for optimization.

**Comment by nicolas-zozol** [comment]
It looks like big samples are more affected:
=====

JSON Sample Alone

master: 1537ms
result-combiner: 3314 ms
----
All but Json Sample

result-combiner: 521ms
master : 417ms

**Comment by nicolas-zozol** [comment]
`y.drop()` is cool, but `thenLeft()` and `thenRight()` are still cool too, especially in long sentences ! I will rename them `thenKeep()` and `thenDrop()` if you see no objection.

**Comment by d-plaindoux** [comment]
I think the underlying semantic is not clear and exact if we rename thenLeft and thenRight

For instance:
- a.thenLeft(b)   => parse with a and b and return result a
- a.thenRight(b) => parse with a and b and return result b

What about:
- a.thenKeep(b) => ? 
- a.thenDrop(b) => ?

**Comment by nicolas-zozol** [comment]
- a.thenKeep(b) =>parse with a and b and keep result b (so drop result a)
- a.thenDrop(b) => parse with a and b and drop result b (so keep result a)

In both case, I think it's quite hard to explain to a beginner, that's why `y.drop()` is great . If it doesn't feel right for theory, it's probably safer to keep status quo.

**Comment by d-plaindoux** [comment]
Well removing thenLeft and thenRight might be the right response since it can be replaced using `then`and `drop`.

**Comment by nicolas-zozol** [comment]
Here is a real life example to see the problem with only using drop():

```js
// thenLeft, thenRight
C.string("Hello")
    .then(C.char(' ').rep())
    .then(C.char("'"))
    .thenRight(C.letter.rep()) 
    .thenLeft(C.char("'"));

// thenKeep, thenDrop
C.string("Hello")
    .then(C.char(' ').rep())
    .then(C.char("'"))
    .thenKeep(C.letter.rep())
    .thenDrop(C.char("'"));

//drop
const parser = C.string("Hello")
    .then(C.char(' ').rep())
    .then(C.char("'")).drop()  
    .then(C.letter.rep()) 
    .then(C.char("'").drop());


// Mix
C.string("Hello")
    .then(C.char(' ').rep())
    .then(C.char("'"))
    .thenKeep(C.letter.rep()) // keeping repeated ascii letters
    .then(C.char("'").drop());
```

In my opionion, you just read wich line you keep with `thenKeep()` when you need more comprehension with other forms - obviously thinking is not that bad.
The biggest problem reading this with only `y.drop()`  is that it is not clear at all what exactly we drop : the `then().then()` or just `C.char("'")`. You have to really care about parenthesis for what is very standard to write.

**Comment by nicolas-zozol** [comment]
After a day of thoughts, I think you are right, `thenLeft()` and `thenRight()` should disappear. There would be only the `drop()` concept.
It's up to the coder to make its code readable, but anyway with this parser, he better should.

Moreover, I will make a `ParserAbstractFactory` to allow polymorphism, and another Parser could easily extends the current with `thenLeft`, `thenDrop`.....

**Comment by nicolas-zozol** [comment]
I am able to remove the use of `list()` and `value.array()`. It works with around 20 tests.

```js
class Parser{

 _value(p1,a,p2,b){
        //console.log('types:',p1.type.toString(), p2.type.toString());
        switch (p1.type){
            case types.ARRAY:{
                switch (p2.type){
                    case types.ARRAY: return [...a,...b];
                    case types.DROPPED: return a;
                    case types.SIMPLE: return [...a, b];
                    throw "unknown type "+p2.type.toString();
                }
            }
            case types.SIMPLE:{
                switch (p2.type){
                    case types.ARRAY: return [a,...b];
                    case types.DROPPED: return a;
                    case types.SIMPLE: return [a, b];
                    throw "unknown type "+p2.type.toString();
                }
            }
            case types.DROPPED:{
                switch (p2.type){
                    case types.ARRAY: return b;
                    case types.DROPPED: return []; //dropped anyway
                    case types.SIMPLE: return [b];
                    throw "unknown type "+p2.type.toString();
                }
            }
            throw "unknown type "+p1.type.toString();
        }
    }
}


export class ArrayParser extends Parser{

    constructor(parse){
        super();
        this.parse = parse.bind(this);
        this.type= types.ARRAY;
    }
}

export class DroppedParser extends Parser{

    constructor(parse){
        super(parse);
        this.type= types.DROPPED;
        this.map(()=>[]);
    }
}
```

**Comment by nicolas-zozol** [comment]
`expect two (optrep) to return [[b,b,b],[a]]`

Is it a good idea ? Isn't it more consistant with the new then to have `[b,b,b,a]` ?
