### ISSUE TITLE
Performance issue

### ISSUE THREAD

**Issue by nicolas-zozol** [d-plaindoux/masala-parser#68]
Since v 0.3, hotelhub automated tests are 10x slower, but the main difference is that their custom code has been wrapped into the Extractor bundle, and that we have split code on bundles.

**Comment by nicolas-zozol** [comment]
with v0.2, we have 355 tests in 881ms, making 2.5 tests/s. With v0.3 we have 403 for 1125 ms, making 2.8 tests/s. 
Removing markdown and extractor bundle tests that may be time consuming, we have 307=>1062, making 3.45 test/s (???)
so the 10x problem is not inside the lib

**Comment by nicolas-zozol** [comment]
I used the JSON parser with the 100k sample. It takes 604ms with v0.2 against 855ms with v0.3. We still have around 10-20% unexplained decrease of perfs. Still don't know why, but it's not the 10x problem.

**Comment by d-plaindoux** [comment]
A profiling does not give us significant results when we use the last code.

[processed.txt](https://github.com/d-plaindoux/parsec/files/912180/processed.txt)

**Comment by nicolas-zozol** [comment]
Not the same problem, but the extractor could do much better:

```js
function wordSequence(stop) {
    return F.not(stop);
}

function wordsUntil(stop) {
    return F.try(
        wordSequence(stop).rep().then(F.eos).thenReturns(undefined)
    ).or(
        wordSequence(stop).rep().map(chars=>chars.join(''))
        )
        .filter(v=> v !== undefined);
}
```
    
Translation: It reads everything, and if not found starts again
With Just reverting: 

```js
 return F.try(
        wordSequence(stop).rep().map(chars=>chars.join(''))
    ).or(
        wordSequence(stop).rep().then(F.eos).thenReturns(undefined)
        )
        .filter(v=> v !== undefined);
```
And I win 200ms: a test takes 400ms instead of 650ms, but it used to be around 50ms

So I guess the problem is on the Stream reader. I may have touched something...

I have to test something that does not read all the text twice, something like:

```js 
const found = wordSequence(stop).rep().map(chars=>chars.join(''))
const notFound = F.eos;
return found.or(notFound.thenReturns(undefined)).filter(v=> v !== undefined);
```

**Comment by nicolas-zozol** [comment]
We should make a test performance for evaluating order of a `F.try(F.try())` depending on the size of the stream.

**Comment by nicolas-zozol** [comment]
We should also mark in the doc which function uses a `try()` so that the user knows where he goes.

**Comment by nicolas-zozol** [comment]
I've made some tests here : https://github.com/nicolas-zozol/class-vs-functions-vs-babel-performances

I thought babel could be a huge factor, but probably not that much. Good job for them.

**Comment by nicolas-zozol** [comment]
I have written in the docs that we should avoid too many long `try()`. I have rewritten my parsers with another mindset, and it's fast again.
