### ISSUE TITLE
Creation of unused parsers

### ISSUE THREAD

**Issue by nicolas-zozol** [d-plaindoux/masala-parser#74]
I'm going deeper in the parser to understand it better. I have this little combinator:

```js
const line = stream.ofString('ooo');
const combinator = C.char('o').rep();
const value = combinator.parse(line).value;
test.deepEqual(value, ['o','o','o']);
```
And putting in `Parser.repeatable()`

```js
function repeatable(self, occurrences, accept) {
    console.log('Parser creation');
    return new Parser((input, index=0) => {
        console.log('Parser used,', index);
        var consumed = false,
            value = [],
...
}
```

The result is that we create 9 parsers and only one has its function executed:

````
Parser creation
Parser creation
Parser creation
Parser creation
Parser creation
Parser creation
Parser creation
Parser creationParser creation
Parser used, 0
```
So what happens to the others ?

**Comment by nicolas-zozol** [comment]
I know why it's here. When exporting functions, we do:

```js

export default {
    parse,
    nop,
    try: doTry,
    any: any(),
    subStream,
    not: not,
    lazy,
    returns,
    error: error(),
    eos: eos(),
    satisfy,
    sequence,
    startsWith,
    moveUntil,
    dropTo,
};
```
So each time we do for example: `any: any()`, we create a Parser at the `import` phase, even before the coder has started to build its parser combinator.

And because at the beginning of Masala, we run: 

```js
export const bundle = {
    data,
    genlex,
    parsec,
    standard,
    Streams,
    parser,
    F,
    C,
    N,
    JSON,
    MD,
    X,
    T,
};
```
we just run all  `any: any()` kind of functions at the very start of all bundles. Looks like the JVM 😄 .

It's not good on performances, but it's a one-shot. A bigger problem is that it makes it much more difficult to debug, because all parsers jumps off everywhere. 

So the question is: 
* Do we keep the shortcuts and drop all unwanted bundles ?
* Do we end every shortcuts, and we'll have to add much more parenthesis in the code.

**Comment by nicolas-zozol** [comment]
I prefer the second option, thought it will make some good refactoring. Better now than later.

**Comment by d-plaindoux** [comment]
The second solution seems to be the best.

**Comment by d-plaindoux** [comment]
Intermediate representation  should be the best response for an interpretative approach of parsers. This is in progress for the moment.

```
p1.then(p2).repeatable(3) => Repeat(3, Then(p1,p2))
``` 

An interpreter then can be designed in order to generate the minimal parser for a given AST.

**Comment by nicolas-zozol** [comment]
I think it's also the case in genlex/token.js. See #103
