### ISSUE TITLE
Usage with MIT-licensed project?

### ISSUE THREAD

**Issue by njlr** [d-plaindoux/masala-parser#83]
I would love to use masala-parser, but my project is MIT and masala-parser is LGPL. LGPL does not require that dependent code is LGPL, provided it is only linked. But what does this mean in the context of JavaScript? 

 * Can I `import` in the ES6-sense? 
 * Can I use minifiers? 
 * Can I use Closure compiler?

**Comment by d-plaindoux** [comment]
Hi, since you are using the library without any modification this is not a problem.

**Comment by njlr** [comment]
Great, thanks.
